""" Module with constants using in space game. """

TIC_TIMEOUT = 0.1
DIM_DURATION = 20
NORMAL_DURATION = 3
BRIGHT_DURATION = 5
STARS_SYMBOLS = '+*.:'
STARS_AMOUNT = 500
BORDER_THICKNESS = 2
START_RANDINT = 0
FRAME_RATE = 15
